# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install .
        python -m pip install coverage codecov
        python -m pip install pytest

    - name: Run coverage
      run: |
        coverage run -m pytest tests
    - name: Run codecov
      if: success()
      env:
        CODECOV_TOKEN: "a2d2aa9f-9b97-4496-b3d5-b6ceb634ecfc"
      run: |
        codecov
